openapi: 3.0.0
info:
  title: BOOKINGSTUDIO_BACKEND
  version: 1.0.0
servers:
  - url: https://bookingstudio.herokuapp.com
  - url: http://localhost:3003
tags:
  - name: District
  - name: BookingUser
  - name: Post
  - name: Partner
paths:
  /api/district:
    get:
      tags:
        - District
      summary: New Request
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/booking-user:
    get:
      tags:
        - BookingUser
      summary: New Request
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '0'
        - name: limit
          in: query
          schema:
            type: integer
          example: '0'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/studio-post:
    get:
      tags:
        - Post
      summary: New Request
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '2'
        - name: limit
          in: query
          schema:
            type: integer
          example: '0'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/register-partner:
    get:
      tags:
        - Partner
      summary: getAll
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '3'
        - name: limit
          in: query
          schema:
            type: integer
          example: '10'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/register-partner/24:
    get:
      tags:
        - Partner
      summary: getPartnerById
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/register-partner/update/24:
    patch:
      tags:
        - Partner
      summary: New Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                PartnerName: Hang Đôi Studio
                RepresentativeName: Hoàng Đức Thắng
                Phone: '0967445997'
                OtherPhone: '0777445997'
                Email: hangdoistudio@gmail.com
                ReEmail: hangdoistudio@gmail.com
                BusinessRegistrationLicenseNumber: 123
                Address: 522 Nguyễn Hữu Thọ, p.Khuê Trung, q.Cẩm Lệ, Tp. Đà Nẵng
                BankBranchName: ACB bank - Chi nhánh Hòa Khánh
                BankAccount: '2412037'
                BankAccountOwnerName: HOANG DUC THANG
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
