openapi: 3.0.0
info:
  title: BOOKINGSTUDIO_BACKEND
  version: 1.0.0
servers:
  - url: https://bookingstudio.herokuapp.com
  - url: http://localhost:3003
tags:
  - name: District
  - name: Partner
  - name: BookingUser
  - name: Studio Post
  - name: Booking
  - name: Room
paths:
  /api/district:
    get:
      tags:
        - District
      summary: Get All District
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/register-partner:
    get:
      tags:
        - Partner
      summary: Get All Partner
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '3'
        - name: limit
          in: query
          schema:
            type: integer
          example: '10'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/register-partner/24:
    get:
      tags:
        - Partner
      summary: Get Partner By Id
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/register-partner/update/24:
    patch:
      tags:
        - Partner
      summary: Update Partner By Id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                PartnerName: Hang Đôi Studio
                RepresentativeName: Hoàng Đức Thắng
                Phone: '0967445997'
                OtherPhone: '0777445997'
                Email: hangdoistudio@gmail.com
                ReEmail: hangdoistudio@gmail.com
                BusinessRegistrationLicenseNumber: 123
                Address: 522 Nguyễn Hữu Thọ, p.Khuê Trung, q.Cẩm Lệ, Tp. Đà Nẵng
                BankBranchName: ACB bank - Chi nhánh Hòa Khánh
                BankAccount: '2412037'
                BankAccountOwnerName: HOANG DUC THANG
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/booking-user:
    get:
      tags:
        - BookingUser
      summary: Get All Booking User
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          example: '0'
        - name: limit
          in: query
          schema:
            type: integer
          example: '0'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/booking-user/5:
    get:
      tags:
        - BookingUser
      summary: Get Booking User By Id
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - BookingUser
      summary: Update Booking User & Block acount send stutus:false
      requestBody:
        content: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/studio-post:
    get:
      tags:
        - Studio Post
      summary: getDetailById
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
          example: '10'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/studio-post/5:
    put:
      tags:
        - Studio Post
      summary: updateById
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                IsDeleted: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/booking:
    get:
      tags:
        - Booking
      summary: Get All Booking
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
          example: '10'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/booking/5:
    get:
      tags:
        - Booking
      summary: Get Booking By Id
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/alaa:
    get:
      tags:
        - Room
      summary: Get All Room
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
